language: cpp
os: linux
dist: bionic



matrix:
  include:
    - name: "clang-9 build test"
      env:
        CXX=clang++-9
        CC=clang-9
        BUILD_TYPE=Debug
      compiler: clang-9
      addons:
        apt:
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
            - ninja-build
            - python3-pip
            - python3-setuptools
            - build-essential
            - libgtest-dev
    - name: "clang-8 build test"
      env:
        CXX=clang++-8
        CC=clang-8
        BUILD_TYPE=Debug
      compiler: clang-8
      addons:
        apt:
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - ninja-build
            - python3-pip
            - python3-setuptools
            - build-essential
            - libgtest-dev
    - name: "clang-7 build test"
      env:
        CXX=clang++-7
        CC=clang-7
        BUILD_TYPE=Debug
      compiler: clang
      addons:
        apt:
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - ninja-build
            - python3-pip
            - python3-setuptools
            - build-essential
            - libgtest-dev
    
    - name: "gcc build test"
      env:
        COMPILER=gcc
        CXX=g++
        CC=gcc
        BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - gcc
            - g++
            - ninja-build
            - python3-pip
            - python3-setuptools
            - build-essential
            - libgtest-dev
    
    # UNDONE: mac xcode build support (brew install python3 ninja is failing)
    # - name: "Mac xcode11(Clang-6) build test"
    #   env: COMPILER=clang++ BUILD_TYPE=Debug
    #   os: osx
    #   osx_image: xcode11
    #   compiler: clang
    #   addons:
    #   homebrew:
    #     packages:
    #     - clang-format
    #     - meson
    #     - ninja
    
    - name: "clang tidy"
      env:
        CXX=clang++-9
        CC=clang-9
        BUILD_TYPE=Debug
      compiler: clang-9
      addons:
        apt:
          packages:
            - clang-9
            - clang-tidy
            - clang-tidy-6.0
            - clang-tools-6.0
            - libc++-dev
            - libc++abi-dev
            - ninja-build
            - python3-pip
            - python3-setuptools
            - build-essential
            - libgtest-dev
      script:
        - mkdir build
        - meson build
        - cd build
        - ninja
        - ninja test
        - ninja tidy

    - name: "clang format"
      env:
        CXX=clang++-9
        CC=clang-9
        BUILD_TYPE=Debug
      compiler: clang-9
      addons:
        apt:
          packages:
            - clang-9
            - clang-format-9
            - libc++-9-dev
            - libc++abi-9-dev
            - ninja-build
            - python3-pip
            - python3-setuptools
            - build-essential
            - libgtest-dev
      script:
        - mkdir build
        - meson build
        - cd build
        - ninja
        - ninja test
        - ninja format
        - |
          if [[ -n $(git diff) ]]; then
            echo "You must run ninja format before submitting a pull request"
            echo ""
            git diff
            exit -1
          fi


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install meson; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install meson; fi

script:
  - mkdir build
  - meson build
  - cd build
  - ninja
  - ninja test
  